version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.13.4
    container_name: gitea
    environment:
      - DOMAIN=gitea.evgeni.icu
        #      - ROOT_URL=gitea.evgeni.icu  # this is causing troubles with the url
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
